version: '3.4'

services: 
    samba:
        container_name: samba
        image: dperson/samba:latest
        environment:
            USERID: 1000
            GROUPID: 1000
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        tmpfs:
            - /tmp
        restart: unless-stopped
        volumes:
            - ${DATA_PATH}:/mnt:z
        command: '-s "Storage;/mnt;yes;no;no;${USER}" -u "${USER};${PASSWORD}" -p'
        mem_limit: 512m
