version: "3"

services:
  sonarr:
    image: hotio/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA_PATH}/sonarr/config:/config
      - ${DATA_PATH}:/data
    ports:
      - 8989:8989
    restart: unless-stopped