version: "3"

services:
  qbittorrent:
    image: hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORTS=8081
    volumes:
      - ${APPDATA_PATH}/qbittorrent/config:/config
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8081:8081
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
        ## HTTP Routers
      - "traefik.http.routers.qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrent-rtr.rule=HostHeader(`qbittorrent.$DOMAIN_NAME`)"
      - "traefik.http.routers.qbittorrent-rtr.tls=true"
        ## HTTP Services
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
      - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8081"
        ## Middlewares
      - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file"