version: "2.1"

services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${APPDATA_PATH}/code-server/config:/config
      - ${APPDATA_PATH}:/appdata
      - ${DATA_PATH}/repos:/repos
      - ../:/repos/containers-pessoais
    ports:
      - 8443:8443
    restart: unless-stopped