version: "2.1"

services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${APPDATA_PATH}/code-server/config:/config
      - ${APPDATA_PATH}:/appdata
      - ${DATA_PATH}/repos:/repos
      - ../:/repos/containers-pessoais
    ports:
      - 8443:8443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
        ## HTTP Routers
      - "traefik.http.routers.codeserver-rtr.entrypoints=https"
      - "traefik.http.routers.codeserver-rtr.rule=HostHeader(`code-server.$DOMAIN_NAME`)"
      - "traefik.http.routers.codeserver-rtr.tls=true"
        ## HTTP Services
      - "traefik.http.routers.codeserver-rtr.service=codeserver-svc"
      - "traefik.http.services.codeserver-svc.loadbalancer.server.port=8443"
        ## Middlewares
      - "traefik.http.routers.codeserver-rtr.middlewares=chain-oauth@file"