version: '3'

services:
  pihole:
    extends:
      service: pihole
      file: pihole/docker-compose.yml
    networks:
      outside:
        ipv4_address: ${PIHOLE_IP}
  portainer:
    extends:
      service: portainer
      file: portainer/docker-compose.yml

networks:
  outside:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.0.1/24
          gateway: 192.168.0.1
        - subnet: 2804:14C:F287:9060::/64
          gateway: 2804:14C:F287:9060::1