version: "3"

services:
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA_PATH}/ombi/config:/config
      - ${DATA_PATH}:/data
    ports:
      - 3579:3579
    restart: unless-stopped