version: "3"

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    ports: 
        - "32400:32400/tcp"
        - "1900:1900/udp"
        - "32410:32410/udp"
        - "32412:32412/udp"
        - "32413:32413/udp"
        - "32414:32414/udp"
        - "32469:32469/tcp"
    environment:
      - TZ=America/Sao_Paulo
      - HOSTNAME=PlexServer
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ALLOWED_NETWORKS=192.168.1.0/24,172.16.0.0/16
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${APPDATA_PATH}/plex/config:/config
      - ${MEDIA_PATH}/data
    restart: unless-stopped