version: "2.1"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    ports: 
        - 32400/tcp
        - 1900/udp
        - 32410/udp
        - 32412/udp
        - 32413/udp
        - 32414/udp
        - 32469/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= ${PLEX_CLAIM}
    volumes:
      - ${APPDATA_PATH}/plex/config:/config
      - ${MEDIA_PATH}/tvseries:/tv
      - ${MEDIA_PATH}/movies:/movies
    restart: unless-stopped