version: "3"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    ports: 
        - "3005:3005/tcp"
        - "32400:32400/tcp"
        - "1900:1900/udp"
        - "32410:32410/udp"
        - "32412:32412/udp"
        - "32413:32413/udp"
        - "32414:32414/udp"
        - "32469:32469/tcp"
    environment:
      - TZ=${TIMEZONE}
      - HOSTNAME=PlexServer
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - ALLOWED_NETWORKS=192.168.1.0/24,172.17.0.0/16,172.21.0.0/16
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=https://plex.$DOMAIN_NAME:443
    volumes:
      - ${APPDATA_PATH}/plex/config:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
        ## HTTP Routers
      - "traefik.http.routers.plex-rtr.entrypoints=https"
      - "traefik.http.routers.plex-rtr.rule=HostHeader(`plex.$DOMAIN_NAME`)"
      - "traefik.http.routers.plex-rtr.tls=true"
        ## HTTP Services
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
        ## Middlewares
      - "traefik.http.routers.plex-rtr.middlewares=chain-oauth@file"