version: "3"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: bridge
    ports: 
        - "3005:3005/tcp"
        - "32400:32400/tcp"
        - "1900:1900/udp"
        - "32410:32410/udp"
        - "32412:32412/udp"
        - "32413:32413/udp"
        - "32414:32414/udp"
        - "32469:32469/tcp"
    environment:
      - TZ=America/Sao_Paulo
      - HOSTNAME=PlexServer
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - ALLOWED_NETWORKS=192.168.1.0/24,172.16.0.0/16
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${APPDATA_PATH}/plex/config:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped