version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-64-homeassistant:latest
    volumes:
      - ${APPDATA_PATH}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true