version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "443:443/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: ''
      ServerIP: 192.168.0.201
      ServerIPv6: 2804:14C:F287:9060::2
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole_network:
        ipv4_address: 192.168.0.201
        ipv6_address: 2804:14C:F287:9060::2
    dns:
      - 127.0.0.1
      - 192.168.0.1

networks:
  pihole_network:
    enable_ipv6: true
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.0.1/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.202/30
        - subnet: 2804:14C:F287:9060::/64
          gateway: 2804:14C:F287:9060::1
          ip_range: 2804:14c:f287:9060:0000:0000:0000:0003/80
