version: "3"

services:
  radarr:
    image: hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA_PATH}/radarr/config:/config
      - ${DATA_PATH}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
        ## HTTP Routers
      - "traefik.http.routers.radarr-rtr.entrypoints=https"
      - "traefik.http.routers.radarr-rtr.rule=HostHeader(`radarr.$DOMAIN_NAME`)"
      - "traefik.http.routers.radarr-rtr.tls=true"
        ## HTTP Services
      - "traefik.http.routers.radarr-rtr.service=radarr-svc"
      - "traefik.http.services.radarr-svc.loadbalancer.server.port=7878"
        ## Middlewares
      - "traefik.http.routers.radarr-rtr.middlewares=chain-oauth@file"