version: "2.1"

services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - URL=${PROXY_URL}
      - SUBDOMAINS=,
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
    volumes:
      - ${APPDATA_PATH}/swag/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped