version: "3"

services:
  bazarr:
    image: hotio/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA_PATH}/bazarr/config:/config
      - ${DATA_PATH}:/data
    ports:
      - 6767:6767
    restart: unless-stopped