services:
  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:2.2-arm64
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - PROVIDERS_GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - SECRET=$OAUTH_SECRET
      # INSECURE_COOKIE is required if not using a https entrypoint
    #   - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
      - COOKIE_DOMAIN=${DOMAIN_NAME}
      - AUTH_HOST=oauth.${DOMAIN_NAME}
      - URL_PATH=/_oauth
      - WHITELIST=$MY_EMAIL
      - LIFETIME=2592000 # 30 days
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
        ## HTTP Routers
      - "traefik.http.routers.oauth-rtr.entrypoints=https"
      - "traefik.http.routers.oauth-rtr.rule=HostHeader(`oauth.$DOMAIN_NAME`)"
      - "traefik.http.routers.oauth-rtr.tls=true"
        ## HTTP Services
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"
        ## Middlewares
      - "traefik.http.routers.oauth-rtr.middlewares=chain-oauth@file"
    ports:
     - 4181
